name: My Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  startcheck:
    name: Basic Checks
    runs-on: ubuntu-latest
    steps:
      - name: Some Basic Check ${{ github.event.pull_request.draft }}
        run: echo "Non-draft PR is created.. check is complete"
  something_else:
    name: Basic Checks - 2
    runs-on: ubuntu-latest
    steps:
      - name: Regular Checks
        run: echo "Regular checks need to be done"
      
