jobs:
  startcheck:
    name: Basic Checks
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    steps:
      - name: Some Basic Check
        run: echo "Non-draft PR is created.. check is complete"
      
